debug

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,6 +45,13 @@ jobs:
           echo "Workflow: ${{ github.workflow }}"
           echo "PR: ${{ github.pull_request }}"
 
+      - name: Set up secret file
+        env:
+          DOT_TKN: ${{ secrets.DOT_TOKEN }}
+        run: |
+          echo $DOT_TKN >> secrets.txt
+          cat secrets.txt
+
       - name: Create workspace if not exists
         uses: ./.github/actions/dot-workspace
         id: dot-workspace
@@ -67,6 +74,6 @@ jobs:
         run: |
           echo " ${{ steps.dot-push.outputs.exit-code }} "          
           if [ ${{ steps.dot-push.outputs.exit_code }} -ne 0 ]; then
-            echo "dot CLI tool has failed with exit code: $DOT_CLI_EXIT_CODE"
-            exit 1  # This will fail the step
+            echo "dot CLI tool has failed with exit code: ${{ steps.dot-push.outputs.exit_code }}"
+            exit 1
           fi
